@baseUrl = http://localhost:800/api-monts-et-lacs-81/www/

GET {{baseUrl}}users
###
POST {{baseUrl}}orders/guest
content-type: application/json

{
  "guest": {
    "name": "Jean Dupont",
    "email": "jean.dupont@example.com",
    "phone": "0612345678"
  },
  "items": [
    { "product_id": 1, "quantity": 2, "price": 10.5 },
    { "product_id": 4, "quantity": 6, "price": 20 }
  ]
}
###
#GET http://localhost:3000/auth
#content-type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbTBtaGE2dWgwMDAwNXJnaHlpN21wb2hkIiwiaWF0IjoxNzI1MzcwODk0LCJleHAiOjE3Mjc5NjI4OTR9.OVBu5lc_QfOvg1-oFBuQZnUX-yfdRCggC7oTmwaka3c
###
