@baseUrl = http://localhost:800/api-monts-et-lacs-81/www/

GET {{baseUrl}}users
###
GET {{baseUrl}}users/1
###
GET {{baseUrl}}orders
###
GET {{baseUrl}}orders/5
###
GET {{baseUrl}}products
###
GET {{baseUrl}}cart
###
POST {{baseUrl}}orders/guest
content-type: application/json

{
  "guest": {
    "name": "Antoines GERMINAL",
    "email": "tonin@hotmail.es",
    "phone": "0633991190"
  },
  "items": [
    { "product_id": 4, "quantity": 20, "price": 1.5 },
    { "product_id": 2, "quantity": 13, "price": 1.3 }
  ]
}
###
POST {{baseUrl}}orders/guest
content-type: application/json

{
  "guest": {
    "name": "Lucien Durand",
    "email": "lulu@la.fr",
    "phone": "0790999999"
  },
  "items": [
    { "product_id": 2, "quantity": 3, "price": 15 },
    { "product_id": 3, "quantity": 2, "price": 2.05 },
    { "product_id": 1, "quantity": 3, "price": 12.3 }
  ]
}
###
#GET http://localhost:3000/auth
#content-type: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbTBtaGE2dWgwMDAwNXJnaHlpN21wb2hkIiwiaWF0IjoxNzI1MzcwODk0LCJleHAiOjE3Mjc5NjI4OTR9.OVBu5lc_QfOvg1-oFBuQZnUX-yfdRCggC7oTmwaka3c
###
